os: linux
dist: xenial
language: java

env:
  - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

# Run before every job
before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk
  - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
  - java -version
  - uname -a
  - chmod +x pom.xml

# Only running report_coverage (after merge) to master branch
stages:
  - test
  - name: report_coverage
    if: branch = main AND type != pull_request

# List of jobs to run, tied to specific stages
jobs:
  include:
    - stage: test
      name: UnitTests
      script:
        - mvn test
    - stage: report_coverage
      name: report_coverage
      # Generating test coverage report and publishing to Codacy
      script:
        - mvn jacoco:prepare-agent test jacoco:report -B
        - curl -Ls -o codacy-coverage-reporter-assembly.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/6.0.2/codacy-coverage-reporter-6.0.2-assembly.jar
        - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r target/site/jacoco/jacoco.xml
