name: Maven CI with Coverage Reporting

on:
  push:
    branches: [ "main" ]

jobs:
  report-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Build with Maven and check test coverage
        run: mvn clean verify

      - name: Report coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-report: target/site/jacoco/jacoco.xml